

INSERT INTO ORGANISATION (ID, EMAIL_ADDRESS, IS_DONOR, IS_VALIDATED, CITY, POST_CODE, STREET_NAME, STREET_NUMBER, ORGANISATION_NAME, PHONE_NUMBER) 
VALUES (1, 'orga1@orange.fr', true, true, 'Paris', '75008', 'Rue Saint Bernard', '8-10', 'Orga1', '+033145232302');
INSERT INTO ORGANISATION (ID, EMAIL_ADDRESS, IS_DONOR, IS_VALIDATED, CITY, POST_CODE, STREET_NAME, STREET_NUMBER, ORGANISATION_NAME, PHONE_NUMBER) 
VALUES (2, 'orga2@orange.fr', false, true, 'Paris', '75011', 'Rue Voltaire', '6 bis', 'Orga2', '+033145123025');

INSERT INTO COLLECTION_SPOT_ADDRESS (ID, CITY, POST_CODE, SPOT_NAME, STREET_NAME, STREET_NUMBER) VALUES (1,'Paris', '75008', 'Dépôt Paris 08', 'Rue Saint Bernard', '8-10');
INSERT INTO COLLECTION_SPOT_ADDRESS (ID, CITY, POST_CODE, SPOT_NAME, STREET_NAME, STREET_NUMBER) VALUES (2,'Lyon', '69000', 'Dépôt Lyon 03', 'Rue Lecombe', '17 ter');
INSERT INTO COLLECTION_SPOT_ADDRESS (ID, CITY, POST_CODE, SPOT_NAME, STREET_NAME, STREET_NUMBER) VALUES (3,'Marseille', '13000', 'Dépôt Marseille 01', 'Allée des orangers', '3');

INSERT INTO ORGANISATION_ADDRESS_MAPPING (ORGANISATION_ID, ADDRESS_ID) VALUES (1,1);
INSERT INTO ORGANISATION_ADDRESS_MAPPING (ORGANISATION_ID, ADDRESS_ID) VALUES (2,2);
INSERT INTO ORGANISATION_ADDRESS_MAPPING (ORGANISATION_ID, ADDRESS_ID) VALUES (2,3); 