

INSERT INTO PRODUCT_BATCH (ID, NAME, DESCRIPTION, QUANTITY, UNIT_OF_MEASURE, TO_BE_USED_BY, DONOR_ID, DATE_OF_COLLECTION, IS_AVAILABLE, IS_AWAITING_FOR_COLLECTION) 
VALUES (1, 'Carrots', 'Nice Carrots', '0.3', 'KG', '2019-10-15 10:00:00', 1, '2019-09-15 10:00:00', true, true);

INSERT INTO PRODUCT_BATCH (ID, NAME, DESCRIPTION, QUANTITY, UNIT_OF_MEASURE, TO_BE_USED_BY, DONOR_ID, DATE_OF_COLLECTION, IS_AVAILABLE, IS_AWAITING_FOR_COLLECTION) 
VALUES (2, 'Potatoes', 'Great Potatoes', '50.75', 'KG', '2019-10-18 10:00:00', 1, '2019-09-15 10:00:00', true, true);

INSERT INTO PRODUCT_BATCH (ID, NAME, DESCRIPTION, QUANTITY, UNIT_OF_MEASURE, TO_BE_USED_BY, DONOR_ID, DATE_OF_COLLECTION, IS_AVAILABLE, IS_AWAITING_FOR_COLLECTION) 
VALUES (3, 'Olive oil', 'Premium extra olive oil', '18', 'LITER', '2021-03-01 10:00:00', 2, '2019-09-15 10:00:00', false, false);

INSERT INTO PRODUCT_BATCH (ID, NAME, DESCRIPTION, QUANTITY, UNIT_OF_MEASURE, TO_BE_USED_BY, DONOR_ID, DATE_OF_COLLECTION, IS_AVAILABLE, IS_AWAITING_FOR_COLLECTION) 
VALUES (4, 'Bread', 'Soft square bread', '4', 'KG', '2019-10-15 10:00:00', 1, '2019-09-15 10:00:00', true, false);

INSERT INTO PRODUCT_BATCH (ID, NAME, DESCRIPTION, QUANTITY, UNIT_OF_MEASURE, TO_BE_USED_BY, DONOR_ID, DATE_OF_COLLECTION, IS_AVAILABLE, IS_AWAITING_FOR_COLLECTION) 
VALUES (5, 'Potatoes', 'Great Potatoes', '50.75', 'KG', '2019-10-18 10:00:00', 1, '2019-09-15 10:00:00', true, false);

INSERT INTO PRODUCT_BATCH_STORAGE_CONTAINER_MAPPING (PRODUCT_BATCH_ID, STORAGE_CONTAINER_ID) VALUES (1,1);
INSERT INTO PRODUCT_BATCH_STORAGE_CONTAINER_MAPPING (PRODUCT_BATCH_ID, STORAGE_CONTAINER_ID) VALUES (1,2);
INSERT INTO PRODUCT_BATCH_STORAGE_CONTAINER_MAPPING (PRODUCT_BATCH_ID, STORAGE_CONTAINER_ID) VALUES (1,3);

INSERT INTO PRODUCT_BATCH_STORAGE_CONTAINER_MAPPING (PRODUCT_BATCH_ID, STORAGE_CONTAINER_ID) VALUES (2,4);

INSERT INTO PRODUCT_BATCH_STORAGE_CONTAINER_MAPPING (PRODUCT_BATCH_ID, STORAGE_CONTAINER_ID) VALUES (3,5);
INSERT INTO PRODUCT_BATCH_STORAGE_CONTAINER_MAPPING (PRODUCT_BATCH_ID, STORAGE_CONTAINER_ID) VALUES (3,6);

INSERT INTO PRODUCT_BATCH_STORAGE_CONTAINER_MAPPING (PRODUCT_BATCH_ID, STORAGE_CONTAINER_ID) VALUES (4,11);
INSERT INTO PRODUCT_BATCH_STORAGE_CONTAINER_MAPPING (PRODUCT_BATCH_ID, STORAGE_CONTAINER_ID) VALUES (5,12);

