

INSERT INTO give_away_crud.GIVE_AWAY (ID, AVAILABLE_TO_BE_COLLECTED_FROM, COLLECTION_DATE, IS_COLLECTED, ORGANISATION_ID, CITY, POST_CODE, SPOT_NAME, STREET_NAME, STREET_NUMBER) 
VALUES (1, '2019-07-15 10:00:00', '2019-07-15 11:00:00', 'false' , 1, 'Paris', '75008', 'home office','Rue Saint Bernard', '8-10');
INSERT INTO give_away_crud.GIVE_AWAY (ID, AVAILABLE_TO_BE_COLLECTED_FROM, COLLECTION_DATE, IS_COLLECTED, ORGANISATION_ID, CITY, POST_CODE, SPOT_NAME, STREET_NAME, STREET_NUMBER) 
VALUES (2, '2019-07-17 10:00:00', '2019-07-17 11:00:00', true, 1, 'Paris', '75008', 'home office' ,'Rue Saint Bernard', '8-10');
INSERT INTO give_away_crud.GIVE_AWAY (ID, AVAILABLE_TO_BE_COLLECTED_FROM, ORGANISATION_ID, CITY, POST_CODE, SPOT_NAME, STREET_NAME, STREET_NUMBER) 
VALUES (3, '2019-07-21 14:00:00', 1, 'Paris', '75008', 'home office', 'Rue Saint Bernard','8-10');

INSERT INTO give_away_crud.CONTAINER (ID, ACCEPTED, COLLECTION_RUN_ID, DESCRIPTION, IS_COLLECTED, GIVE_AWAY_ID) VALUES (1, true, 1, 'carrots', false,1);
INSERT INTO give_away_crud.CONTAINER (ID, ACCEPTED, COLLECTION_RUN_ID, DESCRIPTION, IS_COLLECTED, GIVE_AWAY_ID) VALUES (2, false, 1, 'potatoes', false,1);
INSERT INTO give_away_crud.CONTAINER (ID, ACCEPTED, DESCRIPTION, IS_COLLECTED, GIVE_AWAY_ID) VALUES (3, false, 'vodka', false,2);
INSERT INTO give_away_crud.CONTAINER (ID, ACCEPTED, DESCRIPTION, IS_COLLECTED, GIVE_AWAY_ID) VALUES (4, true, 'Milk', false,3);


