

INSERT INTO PRODUCT_REQUEST (ID, PRODUCT_REQUESTED, QUANTITY, UNIT_OF_MEASURE, IS_ACCEPTED) VALUES (1, 'Carrots', '5.75', 'KG', false);
INSERT INTO PRODUCT_REQUEST (ID, PRODUCT_REQUESTED, QUANTITY, UNIT_OF_MEASURE, IS_ACCEPTED) VALUES (2, 'Potatoes', '18', 'KG', false);
INSERT INTO PRODUCT_REQUEST (ID, PRODUCT_REQUESTED, QUANTITY, UNIT_OF_MEASURE, IS_ACCEPTED) VALUES (3, 'Coke', '14.75', 'LITER', true);
INSERT INTO PRODUCT_REQUEST (ID, PRODUCT_REQUESTED, QUANTITY, UNIT_OF_MEASURE, IS_ACCEPTED) VALUES (4, 'Cherry', '14.77', 'KG', true);




