

INSERT INTO REDISTRIBUTION (ID, ORGANISATION_ID, OFFER_ID, IS_COMPLETED) VALUES (1, 2, 1, false);
INSERT INTO REDISTRIBUTION (ID, ORGANISATION_ID, IS_COMPLETED) VALUES (2, 2, false);
INSERT INTO REDISTRIBUTION (ID, ORGANISATION_ID, OFFER_ID, IS_COMPLETED) VALUES (3, 2, 2, true);

INSERT INTO REDISTRIBUTION_PRODUCT_REQUEST_MAPPING (REDISTRIBUTION_ID, PRODUCT_REQUEST_ID) VALUES (1,1);
INSERT INTO REDISTRIBUTION_PRODUCT_REQUEST_MAPPING (REDISTRIBUTION_ID, PRODUCT_REQUEST_ID) VALUES (2,2);
INSERT INTO REDISTRIBUTION_PRODUCT_REQUEST_MAPPING (REDISTRIBUTION_ID, PRODUCT_REQUEST_ID) VALUES (1,3);

INSERT INTO REDISTRIBUTION_PRODUCT_REQUEST_MAPPING (REDISTRIBUTION_ID, PRODUCT_REQUEST_ID) VALUES (3,4);